version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: owh
      POSTGRES_USER: owh
      POSTGRES_PASSWORD: owh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U owh -d owh"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE__URL: postgresql+psycopg://owh:owh@postgres:5432/owh
      ALLOWED_EMAIL_DOMAINS_FILE: /config/allowed_domains.txt
    volumes:
      - ./config/allowed_domains.txt:/config/allowed_domains.txt:ro
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    environment:
      NEXT_PUBLIC_API_PORT: 8000
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:3000"

volumes:
  pgdata:
