/**
 * Hospital data loader — lazily loads per-state JSON bundles.
 *
 * Data lives in ./hospitals/{STATE_CODE}.json (generated by scripts/convert-hospitals-csv.py).
 * Each file is ~6-10 KB and contains hospitals for one Bundesland.
 */

import { GERMAN_STATES } from './constants';

export interface HospitalEntry {
  id: number;
  name: string;
  lat: number;
  lon: number;
  city: string;
}

// Cache loaded state files so we don't re-import
const cache = new Map<string, HospitalEntry[]>();

// Static require map — Metro bundler needs static paths at build time
const STATE_FILES: Record<string, any> = {
  BW: require('./hospitals/BW.json'),
  BY: require('./hospitals/BY.json'),
  BE: require('./hospitals/BE.json'),
  BB: require('./hospitals/BB.json'),
  HB: require('./hospitals/HB.json'),
  HH: require('./hospitals/HH.json'),
  HE: require('./hospitals/HE.json'),
  MV: require('./hospitals/MV.json'),
  NI: require('./hospitals/NI.json'),
  NW: require('./hospitals/NW.json'),
  RP: require('./hospitals/RP.json'),
  SL: require('./hospitals/SL.json'),
  SN: require('./hospitals/SN.json'),
  ST: require('./hospitals/ST.json'),
  SH: require('./hospitals/SH.json'),
  TH: require('./hospitals/TH.json'),
};

/**
 * Get all hospitals for a given state code (e.g., "BY", "NW").
 * Returns [] for unknown state codes.
 */
export function getHospitalsByState(stateCode: string): HospitalEntry[] {
  const cached = cache.get(stateCode);
  if (cached) return cached;

  const data = STATE_FILES[stateCode];
  if (!data) return [];

  const entries: HospitalEntry[] = data as HospitalEntry[];
  cache.set(stateCode, entries);
  return entries;
}

/**
 * Look up a single hospital by its ID. Searches all states.
 * Returns undefined if not found.
 */
export function getHospitalById(id: number): HospitalEntry | undefined {
  // Check cache first
  for (const entries of cache.values()) {
    const found = entries.find((h) => h.id === id);
    if (found) return found;
  }

  // Load all states and search
  for (const code of GERMAN_STATES.map((s) => s.code)) {
    const entries = getHospitalsByState(code);
    const found = entries.find((h) => h.id === id);
    if (found) return found;
  }

  return undefined;
}
