"""add_privacy_architecture_tables

Revision ID: 6d8399490741
Revises: 
Create Date: 2025-12-08 21:10:20.634020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d8399490741'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_domain', sa.String(length=255), nullable=False),
    sa.Column('staff_group', sa.String(length=32), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('actual_hours_worked', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_hospital_domain'), 'reports', ['hospital_domain'], unique=False)
    op.create_table('stats_by_hospital',
    sa.Column('stat_id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('n_users', sa.Integer(), nullable=False),
    sa.Column('avg_planned_hours_noised', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_actual_hours_noised', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_overtime_hours_noised', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('k_min_threshold', sa.Integer(), nullable=False),
    sa.Column('noise_epsilon', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('stat_id'),
    sa.UniqueConstraint('hospital_id', 'period_start', name='uq_stats_hospital_period')
    )
    op.create_index(op.f('ix_stats_by_hospital_hospital_id'), 'stats_by_hospital', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_stats_by_hospital_period_start'), 'stats_by_hospital', ['period_start'], unique=False)
    op.create_table('stats_by_state_specialty',
    sa.Column('stat_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('role_level', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('n_users', sa.Integer(), nullable=False),
    sa.Column('avg_planned_hours_noised', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_actual_hours_noised', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_overtime_hours_noised', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('k_min_threshold', sa.Integer(), nullable=False),
    sa.Column('noise_epsilon', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('stat_id'),
    sa.UniqueConstraint('country_code', 'state_code', 'specialty', 'role_level', 'period_start', name='uq_stats_state_spec_period')
    )
    op.create_index(op.f('ix_stats_by_state_specialty_period_start'), 'stats_by_state_specialty', ['period_start'], unique=False)
    op.create_index(op.f('ix_stats_by_state_specialty_specialty'), 'stats_by_state_specialty', ['specialty'], unique=False)
    op.create_index(op.f('ix_stats_by_state_specialty_state_code'), 'stats_by_state_specialty', ['state_code'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('hospital_id', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('role_level', sa.String(length=50), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_submission_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=True)
    op.create_index(op.f('ix_users_hospital_id'), 'users', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_users_specialty'), 'users', ['specialty'], unique=False)
    op.create_index(op.f('ix_users_state_code'), 'users', ['state_code'], unique=False)
    op.create_table('verification_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_hash', sa.String(length=128), nullable=False),
    sa.Column('email_domain', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_hash', name='uq_verification_email_hash')
    )
    op.create_index(op.f('ix_verification_requests_email_domain'), 'verification_requests', ['email_domain'], unique=False)
    op.create_index(op.f('ix_verification_requests_email_hash'), 'verification_requests', ['email_hash'], unique=False)
    op.create_table('weekly_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('planned_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('client_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('planned_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_work_event_user_date')
    )
    op.create_index(op.f('ix_work_events_date'), 'work_events', ['date'], unique=False)
    op.create_index(op.f('ix_work_events_submitted_at'), 'work_events', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_work_events_user_id'), 'work_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_events_user_id'), table_name='work_events')
    op.drop_index(op.f('ix_work_events_submitted_at'), table_name='work_events')
    op.drop_index(op.f('ix_work_events_date'), table_name='work_events')
    op.drop_table('work_events')
    op.drop_table('weekly_submissions')
    op.drop_index(op.f('ix_verification_requests_email_hash'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_email_domain'), table_name='verification_requests')
    op.drop_table('verification_requests')
    op.drop_index(op.f('ix_users_state_code'), table_name='users')
    op.drop_index(op.f('ix_users_specialty'), table_name='users')
    op.drop_index(op.f('ix_users_hospital_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stats_by_state_specialty_state_code'), table_name='stats_by_state_specialty')
    op.drop_index(op.f('ix_stats_by_state_specialty_specialty'), table_name='stats_by_state_specialty')
    op.drop_index(op.f('ix_stats_by_state_specialty_period_start'), table_name='stats_by_state_specialty')
    op.drop_table('stats_by_state_specialty')
    op.drop_index(op.f('ix_stats_by_hospital_period_start'), table_name='stats_by_hospital')
    op.drop_index(op.f('ix_stats_by_hospital_hospital_id'), table_name='stats_by_hospital')
    op.drop_table('stats_by_hospital')
    op.drop_index(op.f('ix_reports_hospital_domain'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
